### ISSUE TITLE
Downloading Images from ATEM

### ISSUE THREAD

**Issue by adamtow** [Dev1an/Swift-Atem#12]
Now that I've gotten stills to upload properly to the ATEM, what's the procedure for downloading them, given an index?

Is there a `DownloadManager` class that's yet to be written that would take advantage of the `decodeRunLength` method you've implemented in the Media enum?

**Comment by Dev1an** [comment]
Not that I know of. Like all the other data on the ATEM I don’t think you have commands to explicitly retrieve them. They are sent to you when they change and during startup, I think.

**Comment by adamtow** [comment]
Understood. I’ll look into the DataTransfer commands and see what data is coming from the Atem at startup. I was hoping it would be like the audio data, which isn’t sent unless you send a specific command.
