### ISSUE TITLE
New Release from Master

### ISSUE THREAD

**Issue by johanneskares** [Dev1an/Swift-Atem#15]
Fantastic work on this repo, thanks!

I see there's a few new features that are not yet in a release (e.g. being able to listen to disconnects) Will these new changes be put in a formal release, soon?

**Comment by Dev1an** [comment]
I hope to get back and work on this repo in the second half of august.
I will then
 - add proper documentation using DocC
 - release it as V2

When that's done I will merge the open pull requests and release them as a minor version update to V2.

**Comment by Dev1an** [comment]
The most recent updates including readme and API docs are now inside the development branch. There is a [new tagged pre-release](https://github.com/Dev1an/Swift-Atem/releases/tag/2.0.0-alpha.1) that you can try out using `.package(url: "https://github.com/Dev1an/Swift-Atem", from: .init(2, 0, 0, prereleaseIdentifiers: ["alpha"]))`
