### ISSUE TITLE
public name and model in Config:ProductInfo 

### ISSUE THREAD

**Issue by offthegrid-mike** [Dev1an/Swift-Atem#19]
I am using the latest master and would like to obtain how many hardware input (ie: HDMI in) for ATEM mini (for example, ATEM mini has 4 whilst ATEM mini extreme has 8).

I can't find any useful information except `ProductInfo` with name and model enum so that I can obtain it by myself.

Is it possible to public those variables in the master in the future?

https://github.com/Dev1an/Swift-Atem/blob/b1ab46e3e59353cf18a9093b8fc9ed53917f6e47/Sources/Atem/Messages/Configuration.swift#L39-L50

**Comment by Dev1an** [comment]
Yes i've made them public in the [development](https://github.com/Dev1an/Swift-Atem/tree/development) branch. See 729dffde987bd9510111d7b5fca09a7eeba084ca

**Comment by Dev1an** [comment]
But I think what you are looking for is the [`Config.Topology`](https://swift-atem.netlify.app/documentation/atem/message/config/topology) (`"_top"`) command. https://github.com/Dev1an/Swift-Atem/blob/aa62241956aae2090723f646324ec9842f097a31/Sources/Atem/Messages/Configuration.swift#L86-L119
