### ISSUE TITLE
`ConnectionInitiationEnd` message should be public

### ISSUE THREAD

**Issue by martinprot** [Dev1an/Swift-Atem#23]
When I initialize the controller, I would like to know once the init status is OK.
The documentation says : 
> When this connection initiation process is finished the `ConnectionInitiationEnd` message will be sent. From that moment on you know that a connection is succesfully established.

But `ConnectionInitiationEnd` is not declared public, so the following code does not compile.

```swift
self.controller = try Controller(ipAddress: "192.168.0.48") { connection in
      connection.when{ (message: ConnectionInitiationEnd) in
          print(message)
      }
}
```

Solution: add the `public` visibility to ConnectionInitiationEnd struct.

**Comment by maxbaeumle** [comment]
The same message (`InCm`) is available as public struct `Message.Config.InitiationComplete` [here](https://github.com/Dev1an/Swift-Atem/blob/b1ab46e3e59353cf18a9093b8fc9ed53917f6e47/Sources/Atem/Messages/Configuration.swift#L271).
