### ISSUE TITLE
Swift 5 iOS incompatibility

### ISSUE THREAD

**Issue by ReeceRobinson** [Dev1an/Swift-Atem#7]
When compiling a test project with dependency .package(name: "Atem", url: "https://github.com/Dev1an/Swift-Atem", from: "1.0.0"), and target iOS I get the following compile error:

```
.../SourcePackages/checkouts/Swift-Atem/Sources/Atem/Connection.swift:101:33: error: 'random()' is unavailable in Swift: Use arc4random instead.
                let randomNumber = UInt32(Int(random()) % Int(UInt16.max))
                                              ^~~~~~
Darwin.random:2:13: note: 'random()' has been explicitly marked unavailable here
public func random() -> Int
            ^
```
Replacing random() with arc4random() fixes this problem.

Xcode: 11.6
Apple Swift version 5.2.4

**Comment by Dev1an** [comment]
This should be fixed in version "1.1.1"... Can you check if that resolves your issue?
