### ISSUE TITLE
Does not work with newer versions of Atem Software Control

### ISSUE THREAD

**Issue by CaptiveCreeper** [Dev1an/Swift-Atem#8]
I got everything up and running but the Atem Software Control prompts saying "Your Switcher requires a software update" and launches the setup where it cant do anything.
![image](https://user-images.githubusercontent.com/12246311/95284524-fb6c7a00-0823-11eb-8932-d72a78bd22b7.png)

I would just use older versions of Atem Software Control but they dont run on newer versions of macos.

**Comment by Dev1an** [comment]
> I would just use older versions of Atem Software Control but they dont run on newer versions of macos.

Which version of macOS are you referring to? I am running macOS Catalina 10.15.6 (19G2021) with _ATEM Software Control_ 8.2.1 and that seems to work fine on my machine.

Also, if you want to change the version to a newer version, you can just change the Version number here: https://github.com/Dev1an/Swift-Atem/blob/2cb9322d22601ff62b246a217f833786153259ca/Sources/Atem/Utilities/InitialSwitcherStateMessages.swift#L265
That should trick your Blackmagic software into thinking you are using any version you want. 

⚠️ **Notice** that the protocol versions do not match the advertised software versions though. But they refer to an internal protocol number that gets incremented by one minor version almost every time they release new firmware.

**Comment by CaptiveCreeper** [comment]
Im using macOS 10.15.7 and Atem Software Control 8.5. I dont know what version I had before I reinstalled it on Tuesday but am currently downloading 8.2.1 to see if that works any better

EDIT:
After installing 8.2.1 it still gives the same message. What version do you suggest to change to?

**Comment by jpmarotta** [comment]
I'm running into the same issue, trying to run ATEM SC 8.5.3 on MacOS 10.15.7, same result.

Anyone know the major/minor protocol numbers for 8.5.3?

EDIT: Disregard, was able to get it running once I updated Xcode and Swift libraries. Sweet!

**Comment by CaptiveCreeper** [comment]
@jpmarotta Out of curiosity what major and minor version do you have set for 8.5.3? Or what versions updated version of Xcode/Swift libraries did you use to get it to work?

**Comment by Dev1an** [comment]
@CaptiveCreeper major: 2, minor: 30 works for me with version 8.5.3. Do you still experience any problems? Make sure to check out the latest revision on the master branch.
(I know I still haven't made a proper release with all the code that is currently on master. Once I find some time I will try to update the docs and publish a proper release)

I think the protocol version did not change since the ATEM software 8.1.1

**Comment by Dev1an** [comment]
For anyone who falls back on this issue, here is a simple way to see what protocol version your current BMD Atem switchers installation supports.

# Local installation
Run:
```sh
cd /Library/Application\ Support/Blackmagic\ Design/Switchers/BMDSwitcherAPI.bundle/Contents/MacOS/
export VersionCheckMethodName=__ZN12CBMDSwitcher29HandleAtomCapabilitiesVersionEPvP26BEPAtomCapabilitiesVersion
objdump --no-show-raw-insn --print-imm-hex --dis-symname=$VersionCheckMethodName --disassemble-symbols=$VersionCheckMethodName BMDSwitcherAPI | grep cmpl
```
that will output something like
```asm
c2cf:	cmpl	$0x2001b, 0x8(%r15)
```
Here `$0x2001b` indicates the supported version.
 - `0x2` is the major version
 - `0x001b` is the minor version

# Without installation
To lookup a protocol version for a specific software version that you did not install on your computer, download the software from the BMD website and extract the "Install Atem.pkg" with
```sh
pkgutil --expand-full <path to intstaller> /tmp/atemVx
cd /private/tmp/atem7/Switchers.pkg/Payload/Library/Application\ Support/Blackmagic\ Design/Switchers/BMDSwitcherAPI.bundle/Contents/MacOS
export VersionCheckMethodName=__ZN12CBMDSwitcher29HandleAtomCapabilitiesVersionEPvP26BEPAtomCapabilitiesVersion
objdump --no-show-raw-insn --print-imm-hex --dis-symname=$VersionCheckMethodName --disassemble-symbols=$VersionCheckMethodName BMDSwitcherAPI | grep cmpl
```

# Without downloading the installer
If you are lucky and NRKNO has made a dump of an ATEM running your specific software version just look in their connection dumps: [nrkno/tv-automation-atem-connection/src/__tests__/connection](https://github.com/nrkno/tv-automation-atem-connection/tree/c73d646939eab78ad0e0387864f78c13b10a65fd/src/__tests__/connection)
